"use client";
import { FormEvent, useEffect, useState } from "react";
type Member={id:string;name:string;email:string;role:string;active:boolean};
const empty={id:"",name:"",email:"",role:"subadmin",active:true,password:""};
export default function TeamManagement({api,onClose,onSaved}:{api:(path:string,options?:RequestInit)=>Promise<any>;onClose:()=>void;onSaved:()=>Promise<void>}) {
 const [users,setUsers]=useState<Member[]>([]),[root,setRoot]=useState(""),[form,setForm]=useState(empty),[error,setError]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const load=async()=>{const data=await api("/team");setUsers(data.users);setRoot(data.configuredEmail);};
 useEffect(()=>{load().catch(e=>setError(e.message));},[api]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError("");setNotice("");try{await api("/team",{method:form.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setForm(empty);await load();await onSaved();setNotice("Team account saved.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="lw-overlay"><section className="lw-modal lw-team-modal" role="dialog" aria-modal="true" aria-labelledby="team-title"><div className="lw-modal-heading"><div><div className="lw-eyebrow">PEOPLE & ACCESS</div><h2 id="team-title">Manage your sales team</h2></div><button disabled={busy} aria-label="Close team management" onClick={onClose}>✕</button></div><p>Superadmins manage accounts and batch actions. Subadmins work with individual leads, conversations and stages. Everyone shares the lead workspace.</p><div className="lw-root-account"><strong>Configured superadmin</strong><span>{root}</span><small>Credentials managed in server settings.</small></div><div className="lw-team-list">{users.map(user=><button key={user.id} disabled={busy} onClick={()=>{setForm({...user,password:""});setError("");setNotice("");}}><span><strong>{user.name}</strong><small>{user.email}</small></span><span>{user.role}<small>{user.active?"Active":"Disabled"}</small></span><span>Edit →</span></button>)}</div><form onSubmit={save}><h3>{form.id?"Edit account":"Create team account"}</h3><div className="lw-team-grid"><label>Full name<input required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Login email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="subadmin">Subadmin</option><option value="superadmin">Superadmin</option></select></label><label>{form.id?"New password (optional)":"Password"}<input type="password" autoComplete="new-password" required={!form.id} minLength={10} maxLength={200} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label></div><label className="lw-account-active"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Account active</label><small>Changing a password or role, or disabling an account, ends its existing sessions.</small>{error&&<p className="lw-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="lw-modal-actions">{form.id&&<button type="button" disabled={busy} onClick={()=>setForm(empty)}>Cancel edit</button>}<button className="lw-primary" disabled={busy}>{busy?"Saving…":form.id?"Save account":"Create account"}</button></div></form></section></div>;
}
