import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ArrowLeft, GraduationCap, FileCheck2, BookOpen, ExternalLink, CheckCircle2 } from "lucide-react";
import { steps, documents, faqs } from "./content";
import "./scholarship.css";
export const metadata:Metadata={title:"আল-আযহার স্কলারশিপ | বাংলাদেশি শিক্ষার্থীদের আবেদন গাইড",description:"আল-আযহার স্কলারশিপের যোগ্যতা, প্রয়োজনীয় কাগজপত্র, ধাপে ধাপে আবেদন, আরবি প্রস্তুতি ও সরকারি তথ্যসূত্র।",alternates:{canonical:"https://azharitravels.com/al-azhar-scholarship"}};
const notice="https://shed.gov.bd/pages/moedu-scholarships/egyptian-government-scholarships-and-al-azhar-scholarships-for-the-academic-year-2026-to-2027-cdj2v9-6a749f677c173fd32a843086";
const navigation=[["routes","আবেদনপথ"],["eligibility","যোগ্যতা"],["documents","কাগজপত্র"],["steps","আবেদনের ধাপ"],["preparation","প্রস্তুতি"],["costs","সুবিধা ও খরচ"],["faq","প্রশ্নোত্তর"],["sources","সরকারি লিংক"]];
export default function ScholarshipPage(){return <main className="azs hind-siliguri-regular" lang="bn">
<section className="azs-hero"><div className="azs-wrap"><Link className="azs-back" href="/al-azhar-university"><ArrowLeft size={16}/>আল-আযহার বিশ্ববিদ্যালয় পেজ</Link><div className="azs-hero-grid"><div><span className="azs-eyebrow">বাংলাদেশি শিক্ষার্থীদের জন্য</span><h1>আল-আযহার<br/><span>স্কলারশিপ গাইড</span></h1><p>যোগ্যতা যাচাই থেকে চূড়ান্ত নিবন্ধন—আপনার আবেদন প্রস্তুতির প্রতিটি ধাপ এক জায়গায়।</p><div className="azs-actions"><a className="azs-button" href="#steps">আবেদনের ধাপ দেখুন <ArrowRight size={18}/></a><a className="azs-button azs-outline" href="#documents">কাগজপত্রের চেকলিস্ট</a></div></div><aside className="azs-hero-card"><GraduationCap size={36}/><h2>তিনটি গুরুত্বপূর্ণ ধাপ</h2>{["ভর্তির যোগ্যতা","প্রযোজ্য মনোনয়ন","চূড়ান্ত অনুমোদন"].map((t,i)=><div className="azs-milestone" key={t}><span>{i+1}</span>{t}</div>)}<p>আবেদন বা মনোনয়ন মানেই স্কলারশিপ নিশ্চিত নয়।</p></aside></div></div></section>
<div className="azs-wrap"><nav className="azs-nav" aria-label="স্কলারশিপ গাইডের বিভাগ">{navigation.map(([id,label])=><a key={id} href={"#"+id}>{label}</a>)}</nav>
<div className="azs-notice"><strong>২০২৬–২৭ বিজ্ঞপ্তি ও সময়সীমা</strong><p>বাংলাদেশ সরকারের বৃত্তি তালিকায় ২০২৬–২৭ শিক্ষাবর্ষের বিজ্ঞপ্তি রয়েছে। আবেদন গ্রহণ চলছে কি না ও শেষ তারিখ সরাসরি সরকারি নির্দেশনা থেকে নিশ্চিত করুন। archive date-কে deadline ধরে নেবেন না। <a href={notice} target="_blank" rel="noopener noreferrer">সরকারি বিজ্ঞপ্তি দেখুন ↗</a></p><small>তথ্যসূত্র যাচাই: ১৬ সেপ্টেম্বর ২০২৬</small></div>
<section id="routes" className="azs-section"><span className="azs-kicker">প্রথমে আপনার পথটি বেছে নিন</span><h2>নতুন আবেদন ও বর্তমান শিক্ষার্থীর আবেদন আলাদা</h2><div className="azs-grid"><article className="azs-card"><span className="azs-chip">বাংলাদেশ থেকে নতুন আবেদন</span><h3>বিদেশে যাওয়ার আগে প্রস্তুতি</h3><p>যোগ্যতা, সরকারি বিজ্ঞপ্তি, অনলাইন আবেদন এবং প্রযোজ্য দূতাবাস/মনোনয়ন প্রক্রিয়া অনুসরণ করুন। এই পেজের মূল ধাপগুলো আপনার প্রস্তুতির জন্য।</p></article><article className="azs-card"><span className="azs-chip azs-purple">মিশরে ইতিমধ্যে অধ্যয়নরত</span><h3>বর্তমান শিক্ষার্থীর জন্য পৃথক নির্দেশনা</h3><p>নিজ খরচে অধ্যয়নরত শিক্ষার্থীদের প্রযোজ্য বৃত্তির বিজ্ঞপ্তি, বর্তমান ফলাফল ও আবাসিক কাগজপত্রের শর্ত যাচাই করতে হবে। দুই ধরনের সময়সীমা এক নয়।</p></article></div></section>
<section id="eligibility" className="azs-section"><span className="azs-kicker">যোগ্যতা ও সমমান</span><h2>আপনার শিক্ষাগত অবস্থান বুঝে আবেদন করুন</h2><div className="azs-grid">{[["স্নাতক / আলিম বা সমমান","স্বীকৃত উচ্চমাধ্যমিক সনদ, উপযুক্ত ফলাফল ও অনুষদের বিষয়ভিত্তিক যোগ্যতা যাচাই করুন। আরবি ও ধর্মীয় অনুষদের জন্য সনদের সমমান গুরুত্বপূর্ণ।"],["কওমি শিক্ষার্থী","দাওরা, মিশকাত বা অন্য সনদ থাকলেই সরাসরি স্নাতকে ভর্তি নিশ্চিত নয়। বর্তমান মুআদালা ও প্রয়োজনীয় placement সম্পর্কে লিখিত তথ্য নিন।"],["HSC / A-Level শিক্ষার্থী","নিজ দেশে বিশ্ববিদ্যালয়ে ভর্তির যোগ্যতা, পড়া বিষয় ও নির্বাচিত অনুষদের গ্রহণযোগ্যতা যাচাই করুন। সব অনুষদে একই শর্ত বা বৃত্তির আসন নেই।"],["মাস্টার্স / পিএইচডি","সংশ্লিষ্ট ডিগ্রি, ট্রান্সক্রিপ্ট, ভাষাদক্ষতা ও প্রযোজ্য গবেষণা প্রস্তাব প্রস্তুত করুন। চলতি মনোনয়ন কোন স্তরের জন্য তা আগে নিশ্চিত করুন।"]].map(([title,text])=><article className="azs-card" key={title}><BookOpen size={22}/><h3>{title}</h3><p>{text}</p></article>)}</div><p className="azs-note">বয়স, পাশের বছর, স্বাস্থ্য ও অন্যান্য শর্ত চলতি বিজ্ঞপ্তি অনুযায়ী যাচাই করুন। বিশেষ পরিস্থিতিতে দূতাবাস/কর্তৃপক্ষের লিখিত ব্যাখ্যা নিন।</p></section>
<section id="documents" className="azs-section"><span className="azs-kicker">ফাইল প্রস্তুতি</span><h2>কাগজপত্রের চেকলিস্ট</h2><p className="azs-intro">এটি প্রস্তুতির তালিকা। আপনার ক্ষেত্রে কোন নথি ও কত কপি লাগবে, তা চলতি বিজ্ঞপ্তি নির্ধারণ করবে। টিকচিহ্ন শুধু এই পেজে আপনার প্রস্তুতি মিলিয়ে দেখার জন্য; এটি আবেদন জমা দেয় না।</p><div className="azs-document-grid">{documents.map(([title,text])=><label className="azs-document" key={title}><input type="checkbox"/><span><strong>{title}</strong><small>{text}</small></span></label>)}</div></section>
<section id="steps" className="azs-section"><span className="azs-kicker">শুরু থেকে শেষ</span><h2>আবেদনের ১২টি ধাপ</h2><ol className="azs-steps">{steps.map(([title,text],i)=><li key={title}><span className="azs-step-number">{String(i+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section>
<section id="preparation" className="azs-section"><span className="azs-kicker">নির্বাচনের প্রস্তুতি</span><h2>আরবি দক্ষতা ও সম্পূর্ণ নথিতে গুরুত্ব দিন</h2><div className="azs-grid"><article className="azs-card"><h3>প্রতিদিনের অনুশীলন</h3><ul>{["আরবিতে নিজের পরিচয় ও ভবিষ্যৎ পরিকল্পনা বলা","আরবি পাঠ বোঝা, লেখা ও অনুবাদ","নাহু–সরফ ও প্রাসঙ্গিক ইসলামি জ্ঞান","শুদ্ধ কুরআন তিলাওয়াত","কেন এই অনুষদে পড়তে চান—তার পরিষ্কার উত্তর"].map(t=><li key={t}>{t}</li>)}</ul></article><article className="azs-card"><h3>জমা দেওয়ার আগে মিলিয়ে নিন</h3><ul>{["প্রতিটি নথি স্পষ্ট ও সম্পূর্ণ","পাসপোর্ট ও সনদের তথ্য এক","সঠিক অনুষদ ও শিক্ষাস্তর নির্বাচন","প্রয়োজনীয় অনুবাদ ও সত্যায়ন সম্পন্ন","আবেদন নম্বর, রসিদ ও কপি সংরক্ষিত"].map(t=><li key={t}>{t}</li>)}</ul></article></div><div className="azs-arabic"><h3>আরবিতে পরিচয়ের একটি নমুনা</h3><p lang="ar" dir="rtl">اسمي … وأنا من بنغلاديش. أرغب في الدراسة بجامعة الأزهر في كلية … لخدمة مجتمعي بعد التخرج.</p><small>নিজের প্রকৃত নাম, যোগ্যতা ও পছন্দের বিষয় ব্যবহার করুন; মুখস্থ উত্তরের অর্থও বুঝে নিন।</small></div></section>
<section id="costs" className="azs-section"><span className="azs-kicker">আর্থিক পরিকল্পনা</span><h2>কোন সুবিধা পাবেন, কোন খরচ রাখবেন?</h2><div className="azs-grid"><article className="azs-card"><CheckCircle2 size={24}/><h3>Award letter-এ যাচাই করবেন</h3><p>টিউশন, আবাসন, খাবার, মাসিক ভাতা, চিকিৎসা ও যাতায়াত—যা অনুমোদিত হবে তা চূড়ান্ত চিঠিতে দেখুন। পুরোনো বছরের ভাতার পরিমাণ বা টিকিটের সুবিধা একই থাকবে ধরে নেবেন না।</p></article><article className="azs-card"><FileCheck2 size={24}/><h3>নিজের প্রস্তুতি বাজেট</h3><p>পাসপোর্ট, স্বাস্থ্য পরীক্ষা, প্রয়োজনীয় clearance, অনুবাদ, সত্যায়ন, ভিসা/আবাসিক আনুষ্ঠানিকতা এবং প্রাথমিক ব্যক্তিগত খরচের প্রস্তুতি রাখুন। টিকিট অন্তর্ভুক্ত কি না আগে যাচাই করুন।</p></article></div><div className="azs-notice"><strong>স্কলারশিপ ও সেবা প্যাকেজ পৃথক</strong><p>কোনো এজেন্সিকে অর্থ দিলেই স্কলারশিপ নিশ্চিত হয় না। সরকারি ফি, প্রাপকের তথ্য ও চূড়ান্ত award letter যাচাই করুন। আযহারী ট্রাভেলসের ভর্তি/ভ্রমণ সহায়তা প্যাকেজের বিস্তারিত আলাদা বিশ্ববিদ্যালয় পেজে রয়েছে।</p><Link href="/al-azhar-university">বিশ্ববিদ্যালয় ও প্যাকেজের তথ্য দেখুন →</Link></div></section>
<section id="faq" className="azs-section"><span className="azs-kicker">প্রশ্নোত্তর</span><h2>আবেদনের আগে সাধারণ প্রশ্ন</h2><div className="azs-faq">{faqs.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
<section id="sources" className="azs-section"><span className="azs-kicker">সরাসরি যাচাই করুন</span><h2>সরকারি তথ্য ও আবেদন লিংক</h2><p className="azs-intro">এই পেজ একটি প্রস্তুতিমূলক গাইড, সরকারি আবেদন ফরম নয়। বর্তমান বিজ্ঞপ্তি আপনার আবেদনপথ ও প্রয়োজনীয় নথি নির্ধারণ করবে।</p><div className="azs-source-list">{[["বাংলাদেশ সরকারের বৃত্তি তালিকা","https://shed.gov.bd/pages/moedu-scholarships"],["২০২৬–২৭ সরকারি বিজ্ঞপ্তি",notice],["আল-আযহারের স্কলারশিপ পেজ","https://azhar.eg/foreignstudent/Scholarship"],["আল-আযহারের ভর্তি ও সমমান নির্দেশনা","https://azhar.eg/foreignstudent/en/Enrollment-and-Registration"],["Study in Egypt পোর্টাল","https://admission.study-in-egypt.gov.eg/"]].map(([title,url])=><a href={url} key={url} target="_blank" rel="noopener noreferrer">{title}<ExternalLink size={17}/></a>)}</div></section>
<section className="azs-footer-cta"><div><h2>বিশ্ববিদ্যালয় সম্পর্কে আরও জানতে চান?</h2><p>অনুষদ, শিক্ষা কাঠামো, ভর্তি ও সেবা প্যাকেজের বিস্তারিত দেখুন।</p></div><div className="azs-actions"><Link className="azs-button" href="/al-azhar-university">বিশ্ববিদ্যালয় পেজ <ArrowRight size={18}/></Link><Link className="azs-button azs-outline" href="/contact">যোগাযোগ করুন</Link></div></section>
</div></main>;}
