import { uploadDay, dayColor } from "../src/app/admin/leads/UploadBadge";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync, mkdirSync, unlinkSync } from "node:fs";
import { resolve } from "node:path";
import { randomUUID } from "node:crypto";
import ExcelJS from "exceljs";
import { NextRequest } from "next/server";
import { decodeLeadText, mapRows, normalizeLeadPhone, parseCsv, readLeadFile } from "../src/app/lib/leadImport";
import { planLeadImport } from "../src/app/lib/leadImportMerge";
import { matchesResponses, responseEntries, responseKey, searchableResponses } from "../src/app/lib/leadResponses";
import { isWhatsappQuestion, whatsappUrl } from "../src/app/lib/whatsapp";

async function main() {
    assert.equal(uploadDay("2026-09-11T18:01:00Z"),"2026-09-12");
    assert.deepEqual(dayColor("2026-09-11T18:01:00Z"),dayColor("2026-09-12T10:00:00Z"));
    assert.notDeepEqual(dayColor("2026-09-11T10:00:00Z"),dayColor("2026-09-12T10:00:00Z"));
    mkdirSync(".data", { recursive: true });
    const path = resolve(`.data/leads-test-${randomUUID()}.db`);
    const db = new DatabaseSync(path);
    for (const migration of ["000001_init", "000002_lead_workspace", "000003_admin_sessions", "000004_lead_followups", "000005_lead_uploads"]) db.exec(readFileSync(`prisma/migrations/${migration}/migration.sql`, "utf8"));
    db.close();
    process.env.DATABASE_URL = `file:${path.replaceAll("\\", "/")}`;
    process.env.ADMIN_API_TOKEN = "lead-test-token";
    const { prisma } = await import("../src/app/lib/db");
    const leadsApi = await import("../src/app/api/admin/leads/route");
    const importApi = await import("../src/app/api/admin/leads/import/route");
    const messagesApi = await import("../src/app/api/admin/leads/[id]/messages/route");
    const audioApi = await import("../src/app/api/admin/leads/audio/[id]/route");
    const request = (method: string, body?: BodyInit, auth = true) => new NextRequest("http://localhost/api/admin/leads", { method, body, headers: auth ? { Authorization: "Bearer lead-test-token" } : {} });
    try {
        assert.deepEqual(parseCsv('\uFEFFName,Notes\r\n"বাংলা, Name","a\nline and ""quote"""'), [["Name", "Notes"], ["বাংলা, Name", 'a\nline and "quote"']]);
        assert.throws(() => parseCsv('Name\n"broken'), /unclosed/);
        assert.throws(() => mapRows([["Other"], ["x"]]), /Name/);
        assert.throws(() => mapRows([["Name", "Name"], ["x", "y"]]), /unique/);
        assert.equal(mapRows([["Name", "Phone"], ["", "1"], ["OK", "+8800123"]]).warnings.length, 1);
        const metaTsv = 'id\tcreated_time\tআপনার_শিক্ষার_মাধ্যম_কোনটি?\t"খরচ,_কে_বহন_করবেন?"\tfull_name\tphone\tretailer_item_id\r\nl:sample\t2026-09-10T00:50:12+06:00\tকওমি\t"পরিবার, নিজের আয়\nদুই মাধ্যমেই"\tইলমের পথিক\tp:+8801320450684\t';
        const le = Buffer.from(metaTsv, "utf16le"), be = Buffer.from(le).swap16();
        for (const bytes of [Buffer.concat([Buffer.from([0xff, 0xfe]), le]), Buffer.concat([Buffer.from([0xfe, 0xff]), be]), le, be, Buffer.from(metaTsv)]) {
            const decoded = await readLeadFile(new File([bytes], "meta-export.csv"));
            assert.equal(decoded.leads.length, 1); assert.equal(decoded.leads[0].name, "ইলমের পথিক");
            assert.equal(decoded.leads[0].phone, "+8801320450684");
            assert.equal(responseEntries(decoded.leads[0].extraFields).length, 2);
            assert.equal(decoded.mapped.find(m => m.field === "name")?.column, "full_name");
        }
        assert.equal(decodeLeadText(Buffer.from("\uFEFFName,Phone", "utf8")), "Name,Phone");
        assert.deepEqual(parseCsv('sep=;\r\nfull_name;phone;answer\r\nTest;+880123;"yes; with help"'), [["full_name", "phone", "answer"], ["Test", "+880123", "yes; with help"]]);
        assert.deepEqual(parseCsv('full_name;phone;answer\nTest;+880123;"yes, with help"'), [["full_name", "phone", "answer"], ["Test", "+880123", "yes, with help"]]);
        const shifted = mapRows([["full_name", "phone", "retailer_item_id"], ["p:+8801608730075", "", ""]]);
        assert.equal(shifted.leads.length, 0); assert.match(shifted.warnings[0], /shifted/);
        const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet("Leads");
        sheet.addRows([["Name", "Phone", "Owner", "Stage"], ["বাংলা Excel", "+880012345", "Test Owner", "Office visit"]]);
        const xlsx = await workbook.xlsx.writeBuffer();
        const excel = await readLeadFile(new File([new Uint8Array(xlsx)], "sample.xlsx"));
        assert.equal(excel.leads[0].phone, "+880012345"); assert.equal(excel.leads[0].name, "বাংলা Excel");
        for (const samplePath of process.argv.slice(2)) {
            const sample = await readLeadFile(new File([readFileSync(samplePath)], "sample.csv"));
            assert.ok(sample.leads.length > 0);
            console.log(`User CSV parsed: ${sample.leads.length} leads; ${sample.mapped.length} mapped fields; ${responseEntries(sample.leads[0].extraFields).length} response questions (read-only).`);
        }
        assert.equal((await leadsApi.GET(request("GET", undefined, false))).status, 401);
        const csv = "Created,Name,Phone,Owner,Stage,Custom\n09/05/2026 10:11pm,বাংলা Test,+880012345,Test Owner,Qualified,Preserved\n09/05/2026,Duplicate,+880012345,Test Owner,Qualified,Duplicate\n09/05/2026,Second,+88009999,Unassigned,New,Other";
        const upload = (commit: boolean) => { const form = new FormData(); form.set("file", new File([csv], "leads.csv")); form.set("commit", String(commit)); return request("POST", form); };
        const preview = await (await importApi.POST(upload(false))).json();
        assert.equal(await prisma.leadUpload.count(),0);
        assert.equal(preview.imported, 2); assert.equal(preview.duplicates, 1); assert.equal(await prisma.lead.count(), 0);
        assert.equal((await (await importApi.POST(upload(true))).json()).imported, 2);
        assert.equal((await (await importApi.POST(upload(true))).json()).imported, 0);
        assert.equal(await prisma.lead.count(), 2);
        const list = await (await leadsApi.GET(request("GET"))).json();
        const lead = list.leads.find((l: { name: string }) => l.name === "বাংলা Test");
        assert.equal(lead.uploads.length,2);
        assert.ok(lead.uploads.every((b:{filename:string;author:string})=>b.filename==="leads.csv"&&b.author));
        assert.notEqual(lead.uploads[0].id,lead.uploads[1].id);
        assert.equal(JSON.parse(lead.extraFields).Custom, "Preserved");
        assert.ok(list.people.some((p: { name: string }) => p.name === "Test Owner"));
        assert.equal((await leadsApi.POST(request("POST", JSON.stringify({ kind: "stage", name: "Office follow-up" })))).status, 200);
        assert.equal((await leadsApi.POST(request("POST", JSON.stringify({ kind: "person", name: "Second Agent" })))).status, 200);
        const ids = list.leads.map((l: { id: string }) => l.id);
        assert.equal((await leadsApi.PATCH(request("PATCH", JSON.stringify({ ids, field: "owner", value: "Second Agent" })))).status, 200);
        assert.equal((await leadsApi.PATCH(request("PATCH", JSON.stringify({ ids: [lead.id], field: "status", value: "Office follow-up" })))).status, 200);
        assert.equal((await leadsApi.PATCH(request("PATCH", JSON.stringify({ ids, field: "owner", value: "Unknown" })))).status, 422);
        const context = { params: Promise.resolve({ id: lead.id }) };
        const form = new FormData(); form.set("party", "customer"); form.set("author", "Customer"); form.set("text", "I will visit the office.");
        // Valid minimal PCM WAV, including the required container signature.
        const wav = Buffer.alloc(46); wav.write("RIFF"); wav.writeUInt32LE(38, 4); wav.write("WAVEfmt ", 8); wav.writeUInt32LE(16, 16); wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22); wav.writeUInt32LE(8000, 24); wav.writeUInt32LE(16000, 28); wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34); wav.write("data", 36); wav.writeUInt32LE(2, 40);
        form.set("audio", new File([wav], "voice.wav", { type: "audio/wav" }));
        assert.equal((await messagesApi.POST(request("POST", form), context)).status, 200);
        const staff = new FormData(); staff.set("party", "staff"); staff.set("author", "Second Agent"); staff.set("text", "Office visit confirmed.");
        assert.equal((await messagesApi.POST(request("POST", staff), context)).status, 200);
        const history = await (await messagesApi.GET(request("GET"), context)).json();
        assert.equal(history.messages.length, 4); assert.equal(history.messages[0].party, "system");
        const voice = history.messages.find((m: { audioType: string }) => m.audioType);
        const voiceContext = { params: Promise.resolve({ id: voice.id }) };
        assert.equal((await audioApi.GET(request("GET", undefined, false), voiceContext)).status, 401);
        const response = await audioApi.GET(request("GET"), voiceContext);
        assert.equal(response.headers.get("Content-Type"), "audio/wav"); assert.deepEqual(Buffer.from(await response.arrayBuffer()), wav);
        const invalid = new FormData(); invalid.set("party", "customer"); invalid.set("author", "Customer"); invalid.set("audio", new File(["<script>bad</script>"], "bad.mp3", { type: "audio/mpeg" }));
        assert.equal((await messagesApi.POST(request("POST", invalid), context)).status, 422);

        // Enrich existing contacts without replacing staff work or conversation history.
        const responseCsv = 'id,created_time,form_name,platform,আপনার_শিক্ষার_মাধ্যম_কোনটি?,খরচ_কে_বহন_করবেন?,full_name,phone,lead_status\nl:test-response,2026-09-05T12:00:00Z,Eligibility,fb,কওমি,পরিবার_বহন_করবে,বাংলা Test,p:+880012345,CREATED';
        const responseUpload = (content: string, commit: boolean) => {
            const form = new FormData(); form.set("file", new File([content], "responses.csv")); form.set("commit", String(commit)); return request("POST", form);
        };
        const responsePreview = await (await importApi.POST(responseUpload(responseCsv, false))).json();
        assert.equal(responsePreview.imported, 0); assert.equal(responsePreview.updated, 1);
        assert.equal(responsePreview.preview[0].action, "Update responses");
        assert.ok(!responseEntries((await prisma.lead.findUniqueOrThrow({ where: { id: lead.id } })).extraFields).some(e => e.answer === "কওমি"));
        assert.equal((await (await importApi.POST(responseUpload(responseCsv, true))).json()).updated, 1);
        const enriched = await prisma.lead.findUniqueOrThrow({ where: { id: lead.id } });
        assert.equal(enriched.owner, "Second Agent"); assert.equal(enriched.status, "Office follow-up");
        assert.equal(await prisma.leadConversation.count({ where: { leadId: lead.id } }), 4);
        assert.equal(await prisma.lead.count(), 2);
        assert.ok(searchableResponses(enriched.extraFields).includes("পরিবার বহন করবে"));
        assert.ok(!responseEntries(enriched.extraFields).some(e => e.key === "platform"));
        const question = responseKey("আপনার_শিক্ষার_মাধ্যম_কোনটি?");
        assert.ok(matchesResponses(enriched.extraFields, [{ question, mode: "equals", answer: "কওমি" }, { question: responseKey("খরচ_কে_বহন_করবেন?"), mode: "contains", answer: "পরিবার" }]));
        assert.ok(!matchesResponses(enriched.extraFields, [{ question, mode: "equals", answer: "জেনারেল" }]));
        assert.ok(matchesResponses("{}", [{ question, mode: "unanswered", answer: "" }]));
        assert.ok(!matchesResponses("{}", [{ question, mode: "answered", answer: "" }]));
        assert.ok(matchesResponses(enriched.extraFields, [{ question, mode: "equals", answer: "", answers: ["কওমি", "জেনারেল"] }]));
        const multiFilters = [{ question, mode: "equals" as const, answer: "", answers: ["কওমি"] }, { question: responseKey("খরচ_কে_বহন_করবেন?"), mode: "equals" as const, answer: "অন্য উত্তর" }];
        assert.ok(matchesResponses(enriched.extraFields, multiFilters, "any"));
        assert.ok(!matchesResponses(enriched.extraFields, multiFilters, "all"));
        assert.ok(!matchesResponses(enriched.extraFields, [multiFilters[1], { question: "", mode: "equals", answer: "" }], "any"));
        assert.equal(whatsappUrl("01322626596"), "https://wa.me/8801322626596");
        assert.equal(whatsappUrl("p:+8801322626596"), "https://wa.me/8801322626596");
        assert.equal(whatsappUrl("০১৩২২৬২৬৫৯৬"), "https://wa.me/8801322626596");
        assert.equal(whatsappUrl("0044 7700 900123"), "https://wa.me/447700900123");
        assert.equal(whatsappUrl("1.32E+09"), null); assert.equal(whatsappUrl("########"), null);
        assert.equal(whatsappUrl("javascript:alert(123456789)"), null);
        assert.ok(isWhatsappQuestion("আপনার_whatsapp/হোয়াটসএ্যাপ_নাম্বারটি_দিন"));
        assert.equal((await (await importApi.POST(responseUpload(responseCsv, true))).json()).updated, 0);
        const older = responseCsv.replace("2026-09-05", "2026-09-01").replace("কওমি", "পুরনো উত্তর");
        assert.equal((await (await importApi.POST(responseUpload(older, true))).json()).updated, 0);
        const blank = responseCsv.replace("কওমি", "");
        assert.equal((await (await importApi.POST(responseUpload(blank, true))).json()).updated, 0);
        const newer = responseCsv.replace("2026-09-05", "2026-09-06").replace("কওমি", "জেনারেল");
        assert.equal((await (await importApi.POST(responseUpload(newer, true))).json()).updated, 1);

        assert.equal(normalizeLeadPhone("p:+8801322626596"), normalizeLeadPhone("01322626596"));
        assert.equal(normalizeLeadPhone("০১৩২২৬২৬৫৯৬"), normalizeLeadPhone("008801322626596"));
        const metaRows = mapRows(parseCsv(responseCsv)).leads;
        assert.equal(metaRows[0].phone, "+880012345"); assert.equal(metaRows[0].form, "Eligibility");
        assert.equal(metaRows[0].status, "New");
        const reverseLead = { ...metaRows[0], id: "reverse" };
        const plainRow = mapRows([["Name", "Phone", "Owner", "Stage"], ["Same person", "+880012345", "Different owner", "Closed"]]).leads;
        const reverse = planLeadImport([reverseLead], plainRow);
        assert.equal(reverse.creates.length, 0); assert.equal(reverse.updates.length, 0);
        const collision = planLeadImport([reverseLead, { ...reverseLead, id: "other", phone: "+880099999", email: "shared@example.com", importKey: "other" }], [{ ...metaRows[0], email: "shared@example.com" }]);
        assert.equal(collision.creates.length, 0); assert.equal(collision.updates.length, 0); assert.equal(collision.warnings.length, 1);
        const local = planLeadImport([{ ...reverseLead, phone: "01322626596", importKey: "local" }], [{ ...metaRows[0], phone: "+8801322626596", importKey: "international" }]);
        assert.equal(local.creates.length, 0);
        const responseWorkbook = new ExcelJS.Workbook();
        responseWorkbook.addWorksheet("Responses").addRows(parseCsv(responseCsv));
        const workbookAnswers = await readLeadFile(new File([new Uint8Array(await responseWorkbook.xlsx.writeBuffer())], "responses.xlsx"));
        assert.equal(planLeadImport([enriched], workbookAnswers.leads).creates.length, 0);
        assert.ok(searchableResponses(workbookAnswers.leads[0].extraFields).includes("কওমি"));
        await prisma.$disconnect();
        assert.equal(await prisma.lead.count(), 2); // Verify persistence after reconnecting.
        const teamApi = await import("../src/app/api/admin/leads/team/route");
        const loginApi = await import("../src/app/api/admin/login/route");
        const authLib = await import("../src/app/lib/adminAuth");
        const account = {name:"Sales Agent",email:"sales@example.test",password:"test-password-123",role:"subadmin",active:true};
        const created = await teamApi.POST(request("POST",JSON.stringify(account)));
        assert.equal(created.status,200);
        const member = (await created.json()).user;
        assert.equal(member.passwordHash,undefined);
        assert.notEqual((await prisma.adminUser.findUniqueOrThrow({where:{id:member.id}})).passwordHash,account.password);
        const login = await loginApi.POST(request("POST",JSON.stringify(account)));
        assert.equal(login.status,200);
        const session = (await login.json()).data.token;
        const sub = (method:string, body?:unknown) => new NextRequest("http://localhost/api/admin/leads",{method,body:body?JSON.stringify(body):undefined,headers:{Authorization:"Bearer "+session}});
        assert.equal((await leadsApi.GET(sub("GET"))).status,200);
        assert.equal((await teamApi.GET(sub("GET"))).status,403);
        assert.equal((await authLib.requireAdmin(sub("GET")))?.status,403);
        const roleIds=(await prisma.lead.findMany()).map(l=>l.id);
        assert.equal((await leadsApi.PATCH(sub("PATCH",{ids:roleIds,field:"status",value:"Qualified"}))).status,403);
        assert.equal((await leadsApi.PATCH(sub("PATCH",{ids:[lead.id],bulk:true,field:"status",value:"Qualified"}))).status,403);
        assert.equal((await leadsApi.DELETE(sub("DELETE",{ids:roleIds,confirmations:3,confirmation:"DELETE 2"}))).status,403);
        assert.equal((await leadsApi.DELETE(sub("DELETE",{ids:[lead.id],bulk:true,confirmations:3,confirmation:"DELETE 1"}))).status,403);
        assert.equal((await leadsApi.PATCH(sub("PATCH",{ids:[lead.id],field:"status",value:"Qualified"}))).status,200);
        assert.equal((await leadsApi.DELETE(sub("DELETE",{ids:[lead.id],confirmations:3,confirmation:"DELETE 1"}))).status,403);
        assert.equal((await leadsApi.PATCH(sub("PATCH",{ids:roleIds,field:"owner",value:"Unassigned"}))).status,403);
        const templatesApi=await import("../src/app/api/admin/leads/templates/route");
        const followupApi=await import("../src/app/api/admin/leads/[id]/followups/route");
        const followupContext={params:Promise.resolve({id:lead.id})};
        const templateData={title:"Qualified follow-up",stage:"Qualified",text:"Hello {name}, your next step is {stage}.",status:"active"};
        const t1=(await (await templatesApi.POST(sub("POST",templateData))).json()).template;
        const t2=(await (await templatesApi.POST(sub("POST",{...templateData,title:"Second message",status:"draft"}))).json()).template;
        assert.equal((await (await templatesApi.GET(sub("GET"))).json()).templates.length,2);
        assert.equal((await templatesApi.PATCH(sub("PATCH",{...t2,status:"archived"}))).status,200);
        assert.equal((await templatesApi.DELETE(sub("DELETE",{id:t1.id,confirmation:"DELETE"}))).status,403);
        assert.equal((await templatesApi.DELETE(request("DELETE",JSON.stringify({id:t2.id,confirmation:"DELETE"})))).status,200);
        assert.equal((await followupApi.PATCH(sub("PATCH",{action:"notes",notes:"Important lead context"}),followupContext)).status,200);
        assert.equal((await followupApi.PATCH(sub("PATCH",{action:"notes",notes:""}),followupContext)).status,403);
        assert.equal((await followupApi.PATCH(sub("PATCH",{action:"add-note",notes:"   "}),followupContext)).status,422);
        assert.equal((await followupApi.PATCH(sub("PATCH",{action:"add-note",notes:"x".repeat(10001)}),followupContext)).status,422);
        for (const notes of ["First separate note", "Second separate note"])
            assert.equal((await followupApi.PATCH(sub("PATCH",{action:"add-note",notes}),followupContext)).status,200);
        const savedNotes = await prisma.leadConversation.findMany({where:{leadId:lead.id,party:"note"}});
        assert.deepEqual(savedNotes.map(n=>n.text).sort(),["First separate note","Second separate note"]);
        assert.ok(savedNotes.every(n=>n.author && n.createdAt));
        const reminderData={action:"create",dueAt:"2026-09-01T09:00:00.000Z",notes:"Call about documents",status:"pending"};
        assert.equal((await followupApi.PATCH(sub("PATCH",{...reminderData,dueAt:"invalid"}),followupContext)).status,422);
        assert.equal((await followupApi.PATCH(sub("PATCH",reminderData),followupContext)).status,200);
        const savedReminder=await prisma.leadReminder.findFirstOrThrow({where:{leadId:lead.id}});
        assert.equal(savedReminder.author,"Sales Agent");
        assert.equal((await followupApi.PATCH(sub("PATCH",{...reminderData,action:"update",id:savedReminder.id,status:"completed"}),followupContext)).status,200);
        assert.ok((await prisma.leadReminder.findUniqueOrThrow({where:{id:savedReminder.id}})).completedAt);
        assert.equal((await followupApi.PATCH(sub("PATCH",{...reminderData,action:"update",id:savedReminder.id,status:"pending",dueAt:"2026-10-01T09:00:00.000Z"}),followupContext)).status,200);
        assert.equal((await prisma.leadReminder.findUniqueOrThrow({where:{id:savedReminder.id}})).completedAt,null);
        const otherLeadId=roleIds.find(id=>id!==lead.id)!;
        assert.equal((await followupApi.PATCH(sub("PATCH",{...reminderData,action:"update",id:savedReminder.id}),{params:Promise.resolve({id:otherLeadId})})).status,404);
        assert.equal((await followupApi.DELETE(sub("DELETE",{id:savedReminder.id,confirmation:"DELETE"}),followupContext)).status,403);
        const trackedLead=(await (await leadsApi.GET(sub("GET"))).json()).leads.find((l:{id:string})=>l.id===lead.id);
        assert.equal(trackedLead.conversations.length,2);assert.ok(trackedLead.conversations.every((n:{text:string})=>n.text.includes("separate note")));
        assert.equal(trackedLead.notes,"Important lead context");assert.equal(trackedLead.reminders.length,1);
        assert.equal((await followupApi.DELETE(request("DELETE",JSON.stringify({id:savedReminder.id,confirmation:"DELETE"})),followupContext)).status,200);
        assert.ok(await prisma.leadConversation.findFirst({where:{leadId:lead.id,text:{startsWith:"Reminder deleted:"}}}));
        const manualApi = await import("../src/app/api/admin/leads/create/route");
        const manual = {name:"Manual contact",phone:"01712345678",email:"manual@example.com",service:"Umrah",notes:"First manual note",owner:"Unassigned",status:lead.status};
        assert.equal((await manualApi.POST(request("POST",JSON.stringify(manual),false))).status,401);
        assert.equal((await manualApi.POST(sub("POST",{...manual,name:" "}))).status,422);
        assert.equal((await manualApi.POST(sub("POST",{...manual,phone:"",email:""}))).status,422);
        assert.equal((await manualApi.POST(sub("POST",{...manual,email:"invalid"}))).status,422);
        assert.equal((await manualApi.POST(sub("POST",{...manual,status:"missing-stage"}))).status,422);
        const manualResponse=await manualApi.POST(sub("POST",manual));assert.equal(manualResponse.status,201);
        const manualId=(await manualResponse.json()).id;
        const manualLead=await prisma.lead.findUniqueOrThrow({where:{id:manualId},include:{conversations:true,uploads:true}});
        assert.equal(manualLead.source,"manual");assert.equal(manualLead.uploads.length,0);
        assert.ok(manualLead.conversations.some(n=>n.party==="note"&&n.text==="First manual note"&&n.author));
        assert.equal((await manualApi.POST(sub("POST",{...manual,phone:"+8801712345678",email:""}))).status,409);
        assert.equal((await manualApi.POST(sub("POST",{...manual,phone:"",email:"MANUAL@example.com"}))).status,409);
        await prisma.leadConversation.deleteMany({where:{leadId:manualId}});await prisma.lead.delete({where:{id:manualId}});
        console.log("PASS: upload previews stay read-only, repeat batches preserve membership, manual lead validation, staff access, duplicate detection and first notes.");
        console.log("PASS: multiple templates and statuses, follow-up schedule/completion/rescheduling, notes, audit history, lead scoping and admin-only deletion/bulk actions.");
        const stageApi=await import("../src/app/api/admin/leads/stages/route");
        assert.equal((await stageApi.PATCH(sub("PATCH",{action:"reorder",ids:[]}))).status,403);
        const managed=await prisma.leadStage.create({data:{name:"Managed test stage",sortOrder:999}});
        const stageTemplate=await prisma.messageTemplate.create({data:{title:"Stage template",stage:managed.name,text:"Next step",status:"active"}});
        await prisma.lead.update({where:{id:lead.id},data:{status:managed.name}});
        assert.equal((await stageApi.DELETE(request("DELETE",JSON.stringify({id:managed.id,confirmation:managed.name})))).status,409);
        assert.equal((await stageApi.PATCH(request("PATCH",JSON.stringify({action:"rename",id:managed.id,name:"Renamed test stage"})))).status,200);
        assert.equal((await prisma.lead.findUniqueOrThrow({where:{id:lead.id}})).status,"Renamed test stage");
        assert.equal((await prisma.messageTemplate.findUniqueOrThrow({where:{id:stageTemplate.id}})).stage,"Renamed test stage");
        assert.ok(await prisma.leadConversation.findFirst({where:{leadId:lead.id,text:"Stage renamed from Managed test stage to Renamed test stage"}}));
        assert.equal((await stageApi.PATCH(request("PATCH",JSON.stringify({action:"rename",id:managed.id,name:"Qualified"})))).status,409);
        const ordered=(await prisma.leadStage.findMany()).map(s=>s.id).reverse();
        assert.equal((await stageApi.PATCH(request("PATCH",JSON.stringify({action:"reorder",ids:ordered})))).status,200);
        assert.deepEqual((await prisma.leadStage.findMany({orderBy:{sortOrder:"asc"}})).map(s=>s.id),ordered);
        assert.equal((await stageApi.PATCH(request("PATCH",JSON.stringify({action:"reorder",ids:ordered.slice(1)})))).status,409);
        await prisma.lead.update({where:{id:lead.id},data:{status:"Qualified"}});
        assert.equal((await stageApi.DELETE(request("DELETE",JSON.stringify({id:managed.id,confirmation:"wrong"})))).status,422);
        assert.equal((await stageApi.DELETE(request("DELETE",JSON.stringify({id:managed.id,confirmation:"Renamed test stage"})))).status,200);
        assert.equal((await prisma.messageTemplate.findUniqueOrThrow({where:{id:stageTemplate.id}})).stage,"");
        console.log("PASS: stage rename preserves leads and history, stage order, role checks, duplicate protection and empty-only removal.");
        const before=(await (await leadsApi.GET(sub("GET"))).json()).leads.map((l:{id:string})=>l.id);
        const note=new FormData();note.set("party","staff");note.set("text","Scroll regression message");note.set("author","Spoofed author");
        const subMessage=new NextRequest("http://localhost/api/admin/leads",{method:"POST",body:note,headers:{Authorization:"Bearer "+session}});
        assert.equal((await messagesApi.POST(subMessage,{params:Promise.resolve({id:lead.id})})).status,200);
        assert.equal((await prisma.leadConversation.findFirstOrThrow({where:{text:"Scroll regression message"}})).author,"Sales Agent");
        assert.deepEqual((await (await leadsApi.GET(sub("GET"))).json()).leads.map((l:{id:string})=>l.id),before);
        assert.equal((await teamApi.PATCH(request("PATCH",JSON.stringify({...account,id:member.id,password:"replacement-password"})))).status,200);
        assert.equal((await leadsApi.GET(sub("GET"))).status,401);
        assert.equal(whatsappUrl("1322626596"),"https://wa.me/8801322626596");
        console.log("PASS: team accounts, password hashing, session invalidation, server-side batch permissions, staff attribution and stable lead ordering.");
        const deletion = (ids: string[], confirmations: number, confirmation: string, auth = true) => request("DELETE", JSON.stringify({ ids, confirmations, confirmation }), auth);
        assert.equal((await leadsApi.DELETE(deletion([lead.id], 3, "DELETE 1", false))).status, 401);
        for (const count of [0, 1, 2]) assert.equal((await leadsApi.DELETE(deletion([lead.id], count, "DELETE 1"))).status, 422);
        assert.equal((await leadsApi.DELETE(deletion([lead.id], 3, "DELETE 2"))).status, 422);
        assert.equal(await prisma.lead.count(), 2);
        assert.equal((await (await leadsApi.DELETE(deletion([lead.id], 3, "DELETE 1"))).json()).deleted, 1);
        assert.equal(await prisma.leadConversation.count({ where: { leadId: lead.id } }), 0);
        assert.equal((await audioApi.GET(request("GET"), voiceContext)).status, 404);
        assert.equal(await prisma.lead.count(), 1);
        assert.equal((await (await leadsApi.DELETE(deletion([lead.id], 3, "DELETE 1"))).json()).deleted, 0);
        const extra = await prisma.lead.create({ data: { name: "Delete test", phone: "", service: "Test", message: "" } });
        const remaining = await prisma.lead.findMany({ select: { id: true } });
        assert.ok(remaining.some(l => l.id === extra.id));
        assert.equal((await (await leadsApi.DELETE(deletion(remaining.map(l => l.id), 3, "DELETE 2"))).json()).deleted, 2);
        assert.equal(await prisma.lead.count(), 0);
        console.log("PASS: CSV/XLSX parsing, response enrichment/preview, idempotency, blank/older answer preservation, phone normalization, ambiguous-match protection, response search/combined filters, preserved assignments/history, protected audio and persistence.");
    } finally {
        await prisma.$disconnect(); unlinkSync(path);
    }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
