"use client";
import { useEffect, useState } from "react";
import { Campaign } from "./page";
import useDebouncedValue from "../leads/useDebouncedValue";
import { qualificationStatuses } from "../../lib/campaigns";
type Row = { id: string; leadId: string; name: string; campaign: string; phone: string; email: string; owner: string; status: string; qualification: string; score: number; step: number; steps: number; completedAt: string | null; createdAt: string; stepName: string; source: string; pending: number; answers: { question: string; answer: unknown }[]; tracking: Record<string, string> };
type Report = { rows: Row[]; total: number; page: number; limit: number; summary: { leads: number; assessments: number; partial: number; qualified: number; converted: number; conversionRate: number; spend: number | null; currency: string | null; costPerLead: number | null; costPerQualifiedLead: number | null }; team: { owner: string; leads: number; pending: number; activity: number; converted: number }[]; ads: { ad: string; leads: number; qualified: number }[]; options: { owners: string[]; services: string[]; statuses: string[]; sources: string[] } };
export default function CampaignReports({ token, campaigns }: { token: string; campaigns: Campaign[] }) {
    const [filters, setFilters] = useState<Record<string, string>>({}), [page, setPage] = useState(1), [data, setData] = useState<Report | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(false), [revision, setRevision] = useState(0), [busy, setBusy] = useState(false);
    useEffect(() => { const lead = new URLSearchParams(window.location.search).get("lead"); if (lead) setFilters({ lead }); }, []);
    const debounced = useDebouncedValue(filters);
    const query = new URLSearchParams({ ...debounced, page: String(page) }).toString();
    useEffect(() => {
        const controller = new AbortController(); setLoading(true); setError("");
        fetch(`/api/admin/campaign-responses?${query}`, { headers: { Authorization: `Bearer ${token}` }, signal: controller.signal, cache: "no-store" }).then(async r => { const p = await r.json(); if (!r.ok) throw new Error(p.error?.message || "Could not load responses."); setData(p.data); }).catch(e => { if (!controller.signal.aborted) setError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
        return () => controller.abort();
    }, [token, query, revision]);
    function filter(key: string, value: string) { setFilters(f => ({ ...f, [key]: value })); setPage(1); }
    async function change(id: string, qualification: string) {
        setBusy(true); setError("");
        try { const r = await fetch("/api/admin/campaign-responses", { method: "PATCH", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ id, qualification }) }); const p = await r.json(); if (!r.ok) throw new Error(p.error?.message || "Could not update."); setRevision(v => v + 1); }
        catch (e) { setError((e as Error).message); } finally { setBusy(false); }
    }
    async function exportCsv() {
        setBusy(true); setError("");
        try { const r = await fetch(`/api/admin/campaign-responses?${query}&export=csv`, { headers: { Authorization: `Bearer ${token}` } }); if (!r.ok) throw new Error("Could not export responses."); const url = URL.createObjectURL(await r.blob()), a = document.createElement("a"); a.href = url; a.download = "campaign-leads.csv"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
        catch (e) { setError((e as Error).message); } finally { setBusy(false); }
    }
    const select = (key: string, title: string, options: string[]) => <label className="campaign-field" key={key}>{title}<select value={filters[key] || ""} onChange={e => filter(key, e.target.value)}><option value="">All</option>{options.map(v => <option key={v}>{v}</option>)}</select></label>;
    return <>
        <section className="campaign-card"><div className="campaign-grid"><label className="campaign-field">Campaign<select value={filters.campaign || ""} onChange={e => filter("campaign", e.target.value)}><option value="">All campaigns</option>{campaigns.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label className="campaign-field">Search contacts, answers or tracking<input value={filters.q || ""} onChange={e => filter("q", e.target.value)} placeholder="Type to search…" /></label></div>
            <details><summary>More filters</summary><div className="campaign-grid">{select("qualification", "Qualification", qualificationStatuses)}{select("owner", "Assigned employee", data?.options.owners || [])}{select("service", "Service", data?.options.services || [])}{select("status", "CRM stage", data?.options.statuses || [])}{select("source", "Source", data?.options.sources || [])}{select("followup", "Follow-up", ["pending", "overdue", "none"])}{["passport", "budget", "location", "education", "experience"].map(key => <label className="campaign-field" key={key}>{key}<input value={filters[key] || ""} onChange={e => filter(key, e.target.value)} placeholder="Answer contains…" /></label>)}{["from", "to"].map(key => <label className="campaign-field" key={key}>{key} (Dhaka)<input type="date" value={filters[key] || ""} onChange={e => filter(key, e.target.value)} /></label>)}{["minScore", "maxScore"].map(key => <label className="campaign-field" key={key}>{key === "minScore" ? "Minimum score" : "Maximum score"}<input type="number" min={0} max={100} value={filters[key] || ""} onChange={e => filter(key, e.target.value)} /></label>)}</div></details>
            <div className="campaign-actions"><button onClick={() => { setFilters({}); setPage(1); }}>Clear filters</button><label>Sort <select value={filters.sort || ""} onChange={e => filter("sort", e.target.value)}><option value="">Newest first</option><option value="oldest">Oldest first</option><option value="score">Highest score</option></select></label><button disabled={busy || loading} onClick={exportCsv}>Export filtered CSV</button><button disabled={loading} onClick={() => setRevision(v => v + 1)}>Refresh</button></div>
        </section>
        {filters.lead && <p>Showing assessments for the selected lead. Clear filters to see all leads.</p>}
        {error && <p role="alert" className="campaign-error">{error}</p>}{loading && <p role="status">Loading responses…</p>}
        {data && <><h2>Campaign lifetime performance</h2><p>These totals use the selected campaign across all dates. Other filters apply to the response list below. Leads are counted once per profile; the response list includes repeat assessments.</p><div className="campaign-stats">{Object.entries({ Leads: data.summary.leads, Assessments: data.summary.assessments, Partial: data.summary.partial, Qualified: data.summary.qualified, Converted: data.summary.converted, "Conversion rate": `${data.summary.conversionRate.toFixed(1)}%`, "Cost / lead": data.summary.costPerLead === null ? "—" : `${data.summary.currency} ${data.summary.costPerLead.toFixed(2)}`, "Cost / qualified": data.summary.costPerQualifiedLead === null ? "—" : `${data.summary.currency} ${data.summary.costPerQualifiedLead.toFixed(2)}` }).map(([label, value]) => <div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><small>Select one campaign to see costs using its manually entered lifetime spend.</small>
            <section className="campaign-card"><h2>Responses ({data.total})</h2>{data.rows.map(r => <article className="campaign-card" key={r.id}><div className="campaign-actions"><div><h3>{r.name}</h3><small>{r.campaign} · {new Date(r.createdAt).toLocaleString()}</small><p>{r.phone || r.email || "Contact not provided yet"}</p></div><a href={`/admin/leads?lead=${encodeURIComponent(r.leadId)}`}>Open lead profile →</a></div><div className="campaign-grid"><div><strong>{r.score}/100</strong><p>{r.completedAt ? "Completed" : `Partial · Step ${r.step + 1}/${r.steps}: ${r.stepName}`}</p><small>Employee: {r.owner} · CRM stage: {r.status} · Pending follow-ups: {r.pending}</small></div><label className="campaign-field">Qualification<select disabled={busy} value={r.qualification} onChange={e => change(r.id, e.target.value)}>{qualificationStatuses.map(s => <option key={s}>{s}</option>)}</select></label></div><details><summary>Answers & source tracking</summary>{r.answers.map((a, i) => <p key={i}><strong>{a.question}</strong><br />{Array.isArray(a.answer) ? a.answer.join(", ") : String(a.answer)}</p>)}{Object.entries(r.tracking).map(([key, value]) => <p key={key} className="preserve-lines"><strong>{key}</strong>: {value}</p>)}</details></article>)}{!data.rows.length && <p>No responses match these filters.</p>}<div className="campaign-actions"><button disabled={loading || page <= 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {Math.max(1, Math.ceil(data.total / data.limit))}</span><button disabled={loading || page * data.limit >= data.total} onClick={() => setPage(page + 1)}>Next</button></div></section>
            <section className="campaign-card"><h2>Team overview</h2><p>Activities include saved notes, conversations and system history. Conversion reflects assessment outcomes.</p><div className="campaign-table-wrap"><table><thead><tr><th>Employee</th><th>Leads</th><th>Pending follow-ups</th><th>Activity entries</th><th>Conversions</th></tr></thead><tbody>{data.team.map(t => <tr key={t.owner}><td>{t.owner}</td><td>{t.leads}</td><td>{t.pending}</td><td>{t.activity}</td><td>{t.converted}</td></tr>)}</tbody></table></div></section>
            <section className="campaign-card"><h2>Campaign / ad set / ad performance</h2><p>Uses URL tracking parameters supplied in your ads. Missing identifiers appear as —.</p><div className="campaign-table-wrap"><table><thead><tr><th>Campaign / ad set / ad</th><th>Leads</th><th>Qualified</th></tr></thead><tbody>{data.ads.map(a => <tr key={a.ad}><td className="preserve-lines">{a.ad}</td><td>{a.leads}</td><td>{a.qualified}</td></tr>)}</tbody></table></div></section>
        </>}
    </>;
}
