"use client";
import { useState } from "react";
import { CampaignConfig, CampaignPage, designFor, pageFor, StepRoute, visibleQuestions, isRequired } from "../../lib/campaigns";
import QuestionInput from "../../campaign/QuestionInput";
import CampaignShell from "../../campaign/CampaignShell";

export default function CampaignDesigner({ config, title, token, onChange, onUploadBusy, mode = "design" }: { mode?: "design" | "routing"; config: CampaignConfig; title: string; token: string; onChange: (c: CampaignConfig) => void; onUploadBusy: (busy: boolean) => void }) {
    const [page, setPage] = useState("step-0"), [mobile, setMobile] = useState(true), [uploading, setUploading] = useState(false), [error, setError] = useState("");
    const design = designFor(config), settings = pageFor(config, page), routes = config.routes || [];
    const pageOptions = [{ key: "intro", label: "Introduction" }, ...config.steps.map((s, i) => ({ key: `step-${i}`, label: `${i + 1}. ${s}` })), { key: "complete", label: "Confirmation" }];
    function updatePage(patch: Partial<CampaignPage>) { onChange({ ...config, pages: { ...config.pages, [page]: { ...config.pages?.[page], ...patch } } }); }
    function route(index: number, patch: Partial<StepRoute>) { onChange({ ...config, routes: routes.map((r, i) => i === index ? { ...r, ...patch } : r) }); }
    async function upload(file: File | undefined, target: "logo" | "page" | "footerImage") {
        if (!file) return; setUploading(true); onUploadBusy(true); setError("");
        try { const body = new FormData(); body.set("file", file); body.set("category", "campaigns"); const r = await fetch("/api/admin/upload", { method: "POST", headers: { Authorization: `Bearer ${token}` }, body }); const result = await r.json(); if (!r.ok) throw new Error(result.error?.message || "Upload failed."); if (target !== "page") onChange({ ...config, design: { ...design, [target]: result.data.url } }); else updatePage({ image: result.data.url }); }
        catch (e) { setError((e as Error).message); } finally { setUploading(false); onUploadBusy(false); }
    }
    return <section className="campaign-designer"><div hidden={mode !== "design"}><div className="campaign-section-heading"><span className="campaign-eyebrow">Make it yours</span><h2>Design studio</h2><p>A consistent brand, with a distinct message on every page.</p></div>
        <div className="campaign-designer-grid"><div><fieldset disabled={uploading}>
            <details open><summary>01 · Brand & appearance</summary><label className="campaign-choice"><input type="checkbox" checked={design.showIntro} onChange={e => onChange({ ...config, design: { ...design, showIntro: e.target.checked } })} />Show introduction before questions</label><small>Off by default so visitors can answer immediately.</small>
                <div className="campaign-color-grid">{([['primary', 'Buttons'], ['accent', 'Accent'], ['background', 'Page'], ['surface', 'Card'], ['text', 'Text']] as const).map(([key, label]) => <label key={key}>{label}<input type="color" value={design[key]} onChange={e => onChange({ ...config, design: { ...design, [key]: e.target.value } })} /></label>)}</div>
                <label className="campaign-field">Rounded corners · {design.radius}px<input type="range" min={0} max={32} value={design.radius} onChange={e => onChange({ ...config, design: { ...design, radius: Number(e.target.value) } })} /></label>
                <label className="campaign-field">Brand name<input value={design.brand} maxLength={1000} onChange={e => onChange({ ...config, design: { ...design, brand: e.target.value } })} /></label><label className="campaign-field">Logo URL<input value={design.logo} onChange={e => onChange({ ...config, design: { ...design, logo: e.target.value } })} /></label><label className="campaign-field">Upload logo<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e => { void upload(e.target.files?.[0], "logo"); e.target.value = ""; }} /></label>
                <label className="campaign-field">Header link<input value={design.homeUrl} onChange={e => onChange({ ...config, design: { ...design, homeUrl: e.target.value } })} /></label><label className="campaign-field">Default footer<textarea value={design.footer} maxLength={1000} onChange={e => onChange({ ...config, design: { ...design, footer: e.target.value } })} /></label><label className="campaign-field">Footer image URL<input value={design.footerImage} onChange={e => onChange({ ...config, design: { ...design, footerImage: e.target.value } })} /></label><label className="campaign-field">Upload footer logo or image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e => { void upload(e.target.files?.[0], "footerImage"); e.target.value = ""; }} /></label><label className="campaign-field">Confirmation button link<input value={design.finishUrl} onChange={e => onChange({ ...config, design: { ...design, finishUrl: e.target.value } })} /></label><label className="campaign-choice"><input type="checkbox" checked={design.showProgress} onChange={e => onChange({ ...config, design: { ...design, showProgress: e.target.checked } })} />Show form progress</label>
            </details>
            <details open><summary>02 · Page header, footer & buttons</summary><label className="campaign-field">Choose a page<select value={page} onChange={e => setPage(e.target.value)}>{pageOptions.map(p => <option key={p.key} value={p.key}>{p.label}</option>)}</select></label>
                <div className="campaign-actions"><label><input type="checkbox" checked={settings.showHeader} onChange={e => updatePage({ showHeader: e.target.checked })} /> Header</label><label><input type="checkbox" checked={settings.showFooter} onChange={e => updatePage({ showFooter: e.target.checked })} /> Footer</label></div>
                {([['heading', 'Heading'], ['description', 'Supporting text'], ['footer', 'Footer text'], ['button', 'Primary button label'], ['backButton', 'Back button label']] as const).filter(([key]) => key !== "backButton" || page.startsWith("step-")).map(([key, label]) => <label key={key} className="campaign-field">{label}<textarea rows={2} maxLength={2000} value={settings[key] ?? ""} placeholder="Leave unset to use the default" onChange={e => updatePage({ [key]: e.target.value || undefined })} /></label>)}
                <label className="campaign-field">Page image URL<input value={settings.image || ""} onChange={e => updatePage({ image: e.target.value })} /></label><label className="campaign-field">Upload page image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e => { void upload(e.target.files?.[0], "page"); e.target.value = ""; }} /></label><small>Images are compressed automatically. Consent is optional and can be removed in Questions.</small>
                <h3>Link buttons on this page</h3><p>Add optional links below the form. Removing a link does not remove the Save / Submit button.</p>
                {(settings.links || []).map((link, index) => <div className="campaign-route-card" key={index}>
                    <label className="campaign-field">Button label<input maxLength={100} value={link.label} onChange={e => updatePage({ links: settings.links!.map((item, i) => i === index ? { ...item, label: e.target.value } : item) })} /></label>
                    <label className="campaign-field">Link URL<input placeholder="https://wa.me/8801318185954 or /contact" value={link.url} onChange={e => updatePage({ links: settings.links!.map((item, i) => i === index ? { ...item, url: e.target.value } : item) })} /></label>
                    <label><input type="checkbox" checked={link.newTab} onChange={e => updatePage({ links: settings.links!.map((item, i) => i === index ? { ...item, newTab: e.target.checked } : item) })} />Open in a new tab</label>
                    <button type="button" onClick={() => updatePage({ links: settings.links!.filter((_, i) => i !== index) })}>Remove button</button>
                </div>)}
                <button type="button" disabled={(settings.links?.length || 0) >= 8} onClick={() => updatePage({ links: [...(settings.links || []), { label: "Contact us", url: "", newTab: true }] })}>+ Add link button</button>
                {page === "complete" && <label className="campaign-choice"><input type="checkbox" checked={settings.showCompletionButton !== false} onChange={e => updatePage({ showCompletionButton: e.target.checked })} />Show confirmation button (requires a confirmation link)</label>}
            </details>
            {error && <p role="alert" className="campaign-error">{error}</p>}{uploading && <p role="status">Uploading image…</p>}
        </fieldset></div><aside className="campaign-preview-panel"><div className="campaign-actions"><strong>Live design preview</strong><button type="button" onClick={() => setMobile(!mobile)}>{mobile ? "Show desktop" : "Show mobile"}</button></div><div className={`campaign-preview ${mobile ? "is-mobile" : ""}`} inert>
            <CampaignShell config={config} title={title || "Your campaign title"} pageKey={page}><div className="campaign-preview-content">
                {page === "intro" ? <p className="preserve-lines">{config.information || "Your campaign information appears here."}</p> : page === "complete" ? <p>{config.confirmation}</p> : visibleQuestions(config, {}).filter(q => q.step === Number(page.replace("step-", ""))).map(q => <QuestionInput key={q.id} question={{ ...q, required: isRequired(q) }} value={undefined} disabled={false} onChange={() => {}} />)}
                {(page !== "complete" || !!design.finishUrl && settings.showCompletionButton !== false) && <button type="button" className="campaign-primary">{settings.button || (page === "intro" ? config.cta : page === "complete" ? "Return to website" : Number(page.replace("step-", "")) === config.steps.length - 1 ? "Submit assessment" : "Save & continue →")}</button>}
            </div></CampaignShell></div><small>Preview uses the same layout and typography as your landing page. Save to apply changes.</small></aside></div>
        </div><details hidden={mode !== "routing"} className="campaign-routing" open><summary>03 · Answer → next step</summary><p>First matching rule wins. Without a match, the default next step is shown. Routes only go forward; required contact steps cannot be skipped.</p>
            <div className="campaign-grid">{config.steps.slice(0, -1).map((s, i) => <label className="campaign-field" key={i}>After {i + 1}. {s}<select value={config.stepNext?.[String(i)] ?? i + 1} onChange={e => onChange({ ...config, stepNext: { ...config.stepNext, [String(i)]: Number(e.target.value) } })}>{config.steps.map((s, j) => j > i ? <option key={j} value={j}>{j + 1}. {s}</option> : null)}</select></label>)}</div>
            {routes.map((r, index) => { const q = config.questions.find(q => q.id === r.questionId); const options = q?.type === "yesno" ? ["Yes", "No"] : q?.type === "consent" ? ["true"] : q?.options || []; return <div className="campaign-route-card" key={index}><span className="campaign-route-number">{index + 1}</span><div className="campaign-grid"><label className="campaign-field">From step<select value={r.from} onChange={e => route(index, { from: Number(e.target.value), questionId: "", answer: "", to: Number(e.target.value) + 1 })}>{config.steps.slice(0, -1).map((s, i) => <option key={i} value={i}>{i + 1}. {s}</option>)}</select></label><label className="campaign-field">When this answer<select value={r.questionId} onChange={e => route(index, { questionId: e.target.value, answer: "" })}><option value="">Choose question</option>{config.questions.filter(q => q.active && q.step === r.from).map(q => <option key={q.id} value={q.id}>{q.label}</option>)}</select></label><label className="campaign-field">Equals{options.length ? <select value={r.answer} onChange={e => route(index, { answer: e.target.value })}><option value="">Choose answer</option>{options.map(o => <option key={o}>{o}</option>)}</select> : <input value={r.answer} onChange={e => route(index, { answer: e.target.value })} />}</label><label className="campaign-field">Show this step next<select value={r.to} onChange={e => route(index, { to: Number(e.target.value) })}>{config.steps.map((s, i) => i > r.from ? <option key={i} value={i}>{i + 1}. {s}</option> : null)}</select></label></div><div className="campaign-actions"><label><input type="checkbox" checked={r.autoAdvance} onChange={e => route(index, { autoAdvance: e.target.checked })} />Continue when answer is selected</label><button type="button" onClick={() => onChange({ ...config, routes: routes.filter((_, i) => i !== index) })}>Remove rule</button></div><small>Automatic navigation waits until required answers on the current step are valid.</small></div>; })}
            <button type="button" disabled={config.steps.length < 2} onClick={() => onChange({ ...config, routes: [...routes, { from: 0, questionId: "", answer: "", to: 1, autoAdvance: false }] })}>+ Add navigation rule</button>
        </details>
    </section>;
}
