"use client";
import { FormEvent, useEffect, useState } from "react";
import { Campaign } from "./page";
import { Question, questionTypes, contactFields, validateConfig } from "../../lib/campaigns";

export default function CampaignEditor({ value, people, busy, onSave, onClose }: { value: Campaign; people: string[]; busy: boolean; onSave: (value: Campaign) => Promise<void>; onClose: () => void }) {
    const [draft, setDraft] = useState(value), [error, setError] = useState(""), [saved, setSaved] = useState("");
    useEffect(() => { setDraft(value); }, [value]);
    function question(index: number, patch: Partial<Question>) { setDraft(d => ({ ...d, config: { ...d.config, questions: d.config.questions.map((q, i) => i === index ? { ...q, ...patch } : q) } })); }
    function move(index: number, delta: number) { const questions = [...draft.config.questions]; [questions[index], questions[index + delta]] = [questions[index + delta], questions[index]]; setDraft({ ...draft, config: { ...draft.config, questions } }); }
    async function submit(event: FormEvent) { event.preventDefault(); setError(""); setSaved(""); try { validateConfig(draft.config); await onSave(draft); } catch (e) { setError((e as Error).message); } }
    return <form onSubmit={submit} className="campaign-card"><fieldset disabled={busy}><div className="campaign-actions"><h2>{draft.id ? "Edit campaign" : "New campaign"}</h2><button type="button" onClick={onClose}>Back to campaigns</button></div>
        <div className="campaign-grid"><label className="campaign-field">Campaign title<input required maxLength={200} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></label><label className="campaign-field">Landing page URL /campaign/<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={80} disabled={!!draft.id} placeholder="al-azhar-admission" value={draft.slug} onChange={e => setDraft({ ...draft, slug: e.target.value })} /><small>Use lowercase letters, numbers and hyphens. Saved URLs stay stable for your ads.</small></label>
            <label className="campaign-field">Service<input maxLength={200} value={draft.service} onChange={e => setDraft({ ...draft, service: e.target.value })} /></label><label className="campaign-field">Assign new leads to<select value={draft.defaultOwner} onChange={e => setDraft({ ...draft, defaultOwner: e.target.value })}>{["Unassigned", ...people].map(p => <option key={p}>{p}</option>)}</select></label>
            <label className="campaign-field">Total campaign spend<input type="number" min={0} step="0.01" value={draft.spend} onChange={e => setDraft({ ...draft, spend: Number(e.target.value) })} /><small>Enter lifetime spend for this campaign; reporting uses the same lifetime period.</small></label><label className="campaign-field">Currency<input required pattern="[A-Z]{3}" maxLength={3} value={draft.currency} onChange={e => setDraft({ ...draft, currency: e.target.value.toUpperCase() })} /></label></div>
        <label className="campaign-choice"><input type="checkbox" checked={draft.published} onChange={e => setDraft({ ...draft, published: e.target.checked })} />Published — accept responses on the public landing page</label>
        <details open><summary>Landing page content</summary>{([['description', 'Short introduction'], ['information', 'Campaign information'], ['cta', 'Start button text'], ['privacy', 'Privacy & progress-saving notice'], ['confirmation', 'Confirmation message']] as const).map(([key, label]) => <label className="campaign-field" key={key}>{label}<textarea maxLength={key === "information" ? 10000 : 2000} value={draft.config[key]} onChange={e => setDraft({ ...draft, config: { ...draft.config, [key]: e.target.value } })} /></label>)}</details>
        <details open><summary>Steps & qualification</summary><label className="campaign-field">Step titles (one per line)<textarea value={draft.config.steps.join("\n")} onChange={e => setDraft({ ...draft, config: { ...draft.config, steps: e.target.value.split("\n") } })} /></label><div className="campaign-grid">{(["hot", "qualified", "warm"] as const).map(key => <label key={key} className="campaign-field">Minimum score: {key}<input type="number" min={0} max={100} value={draft.config.thresholds[key]} onChange={e => setDraft({ ...draft, config: { ...draft.config, thresholds: { ...draft.config.thresholds, [key]: Number(e.target.value) } } })} /></label>)}</div><p>Scores are capped at 100. Completed assessments below Warm become Nurture; a matching disqualification rule overrides the score. Unfinished forms remain Partial.</p></details>
        <h2>Questions</h2><p>Questions appear in this order within their step. Conditions can refer only to earlier questions. Inactive and hidden answers do not count toward qualification.</p>
        {draft.config.questions.map((q, index) => <details className="campaign-card" key={q.id}><summary>{index + 1}. {q.label} · Step {q.step + 1}{!q.active && " · Inactive"}</summary>
            <div className="campaign-actions"><button type="button" disabled={index === 0} onClick={() => move(index, -1)}>↑ Earlier</button><button type="button" disabled={index === draft.config.questions.length - 1} onClick={() => move(index, 1)}>↓ Later</button><button type="button" onClick={() => setDraft({ ...draft, config: { ...draft.config, questions: draft.config.questions.filter((_, i) => i !== index) } })}>Remove question</button></div>
            <label className="campaign-field">Question text<input required maxLength={500} value={q.label} onChange={e => question(index, { label: e.target.value })} /></label>
            <div className="campaign-grid"><label className="campaign-field">Type<select value={q.type} onChange={e => question(index, { type: e.target.value as Question["type"] })}>{questionTypes.map(t => <option key={t}>{t}</option>)}</select></label><label className="campaign-field">Step<select value={q.step} onChange={e => question(index, { step: Number(e.target.value) })}>{draft.config.steps.map((s, i) => <option key={i} value={i}>{i + 1}. {s}</option>)}</select></label><label className="campaign-field">Use answer as<select value={q.field} onChange={e => question(index, { field: e.target.value as Question["field"] })}>{contactFields.map(f => <option value={f} key={f}>{f || "Custom answer"}</option>)}</select></label></div>
            <div className="campaign-actions"><label><input type="checkbox" checked={q.active} onChange={e => question(index, { active: e.target.checked })} /> Active</label><label><input type="checkbox" checked={q.required} onChange={e => question(index, { required: e.target.checked })} /> Required</label></div>
            {["single", "multiple", "select"].includes(q.type) && <label className="campaign-field">Options (one per line)<textarea value={q.options.join("\n")} onChange={e => question(index, { options: e.target.value.split("\n") })} /></label>}
            <div className="campaign-grid"><label className="campaign-field">Show only when<select value={q.condition?.questionId || ""} onChange={e => question(index, { condition: e.target.value ? { questionId: e.target.value, value: "" } : undefined })}><option value="">Always show</option>{draft.config.questions.slice(0, index).filter(p => p.active && p.step <= q.step).map(p => <option key={p.id} value={p.id}>{p.label}</option>)}</select></label>{q.condition && <label className="campaign-field">Answer equals<input value={q.condition.value} maxLength={200} onChange={e => question(index, { condition: { ...q.condition!, value: e.target.value } })} /><small>Use the exact option text, or true for consent. For multiple choice, matches a selected option.</small></label>}</div>
            <h3>Scoring rules</h3>{q.rules.map((r, i) => <div key={i} className="campaign-card"><div className="campaign-grid"><label className="campaign-field">Match<select value={r.operator} onChange={e => question(index, { rules: q.rules.map((rule, ri) => ri === i ? { ...rule, operator: e.target.value as typeof r.operator } : rule) })}>{["equals", "contains", "gte", "lte"].map(op => <option key={op} value={op}>{({ equals: "Equals", contains: "Contains", gte: "Number ≥", lte: "Number ≤" })[op]}</option>)}</select></label><label className="campaign-field">Value<input maxLength={200} value={r.value} onChange={e => question(index, { rules: q.rules.map((rule, ri) => ri === i ? { ...rule, value: e.target.value } : rule) })} /></label><label className="campaign-field">Points<input type="number" min={0} max={100} value={r.points} onChange={e => question(index, { rules: q.rules.map((rule, ri) => ri === i ? { ...rule, points: Number(e.target.value) } : rule) })} /></label></div><div className="campaign-actions"><label><input type="checkbox" checked={r.disqualify} onChange={e => question(index, { rules: q.rules.map((rule, ri) => ri === i ? { ...rule, disqualify: e.target.checked } : rule) })} /> Mark Not Qualified when matched</label><button type="button" onClick={() => question(index, { rules: q.rules.filter((_, ri) => ri !== i) })}>Remove rule</button></div></div>)}
            <button type="button" onClick={() => question(index, { rules: [...q.rules, { operator: "equals", value: "", points: 0, disqualify: false }] })}>+ Scoring rule</button>
        </details>)}
        <button type="button" onClick={() => setDraft({ ...draft, config: { ...draft.config, questions: [...draft.config.questions, { id: crypto.randomUUID(), label: "New question", type: "text", step: 0, required: false, active: true, field: "", options: [], rules: [] }] } })}>+ Add question</button>
        {error && <p role="alert" className="campaign-error">{error}</p>}{saved && <p role="status">{saved}</p>}<div className="campaign-actions"><p>Existing assessments retain the questions and rules they started with.</p><button className="campaign-primary">{busy ? "Saving…" : "Save campaign"}</button></div>
        {draft.id && draft.published && <p><a target="_blank" rel="noopener noreferrer" href={`/campaign/${draft.slug}`}>Open published landing page ↗</a></p>}
    </fieldset></form>;
}
