ALTER TABLE "MediaAsset" ADD COLUMN "visible" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "MediaAsset" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MediaAsset" ADD COLUMN "deletedAt" DATETIME;
ALTER TABLE "MediaAsset" ADD COLUMN "isLocal" BOOLEAN NOT NULL DEFAULT false;
